### PR TITLE
Add commit id to deploy pipeline job

### PR DESCRIPTION
**Pull request by satr**

### CODE REVIEW

**Review by Richard87 — DISMISSED** [review]
lgtm

**Comment by Richard87** [comment]
static check wants these 2 fixed..:

```
pipeline-runner/steps/deploy_test.go:306:2: this value of err is never used (SA4006)
pkg/apis/test/utils.go:156:11: unnecessary assignment to the blank identifier (S1005)
```

**Comment by satr** [comment]
fixed

**Review by Richard87 — APPROVED** [review]
lgtm

**Pull request merged**
